apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-service
  name: dotnet-service
spec:
  selector:
    matchLabels:
      app: dotnet-service

  template:
    metadata:
      labels:
        app: dotnet-service
      annotations:
        sidecar.istio.io/userVolume: '[{ "name": "proto-descriptor", "configMap": { "name": "proto-descriptor", "items": [{ "key": "desc.pb", "path": "desc.pb" }] } }]'
        sidecar.istio.io/userVolumeMount: '[{ "name": "proto-descriptor", "mountPath": "/etc/envoy" }]'
    spec:
      containers:
      - image: oscary/dotnet-service
        name: dotnet-service
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
