apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway-istio
  namespace: istio-system
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: istio-ingressgateway
  template:
    spec:
      containers:
      - name: istio-proxy
        volumeMounts:
        - name: proto-descriptor-vol
          mountPath: /etc/envoy
      volumes:
      - name: proto-descriptor-vol
        configMap:
          name: proto-descriptor
